server:
  port: ${PORT:8761}

spring:
  application:
    name: users-discovery-service

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      default-zone: http://localhost:8761/eureka
  server:
    wait-time-in-ms-when-sync-empty: 0