server:
  port: 0

eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.uuid}}
  client:
    service-url:
      default-zone: http://theusername:thepassword@localhost:8761/eureka

spring:
  application:
    name: account-management-micro-service
  devtools:
    restart:
      enabled: true
