server:
  port: ${PORT:0}

eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.uuid}}
  client:
    service-url:
      default-zone: http://localhost:8761/eureka

spring:
  application:
    name: album-management-micro-service
  devtools:
    restart:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: '*'