server:
  port: ${PORT:0}

eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.uuid}}
  client:
    service-url:
      default-zone: http://theusername:thepassword@localhost:8761/eureka
    register-with-eureka: true

spring:
  application:
    name: user-management-micro-service
  devtools:
    restart:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2-console

management:
  endpoints:
    web:
      exposure:
        include: '*'

## Should be commented as these properties are to be read from config server
user:
  token:
    secret: hfgry463hf746hf57
    expiration-time: 864000000