server:
  port: 8080

spring:
  application:
    name: user-api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

eureka:
  client:
    service-url:
      default-zone: http://theusername:thepassword@localhost:8761/eureka
    register-with-eureka: true


management:
  endpoints:
    web:
      exposure:
        include: info, beans, health, gateway



